/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerificationTechniqueRouteImport } from './routes/verification-technique'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({ id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport } as any)
const VerificationTechniqueRoute = VerificationTechniqueRouteImport.update({ id: '/verification-technique', path: '/verification-technique', getParentRoute: () => rootRouteImport } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({ id: '/mentions-legales', path: '/mentions-legales', getParentRoute: () => rootRouteImport } as any)
const InscriptionRoute = InscriptionRouteImport.update({ id: '/inscription', path: '/inscription', getParentRoute: () => rootRouteImport } as any)
const FormationsRoute = FormationsRouteImport.update({ id: '/formations', path: '/formations', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const AvisRoute = AvisRouteImport.update({ id: '/avis', path: '/avis', getParentRoute: () => rootRouteImport } as any)
const AgenceRoute = AgenceRouteImport.update({ id: '/agence', path: '/agence', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agence' | '/avis' | '/contact' | '/formations' | '/inscription' | '/mentions-legales' | '/verification-technique' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agence' | '/avis' | '/contact' | '/formations' | '/inscription' | '/mentions-legales' | '/verification-technique' | '/sitemap.xml'
  id: '__root__' | '/' | '/agence' | '/avis' | '/contact' | '/formations' | '/inscription' | '/mentions-legales' | '/verification-technique' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenceRoute: typeof AgenceRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  FormationsRoute: typeof FormationsRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  VerificationTechniqueRoute: typeof VerificationTechniqueRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': { id: '/sitemap.xml'; path: '/sitemap.xml'; fullPath: '/sitemap.xml'; preLoaderRoute: typeof SitemapDotxmlRouteImport; parentRoute: typeof rootRouteImport }
    '/verification-technique': { id: '/verification-technique'; path: '/verification-technique'; fullPath: '/verification-technique'; preLoaderRoute: typeof VerificationTechniqueRouteImport; parentRoute: typeof rootRouteImport }
    '/mentions-legales': { id: '/mentions-legales'; path: '/mentions-legales'; fullPath: '/mentions-legales'; preLoaderRoute: typeof MentionsLegalesRouteImport; parentRoute: typeof rootRouteImport }
    '/inscription': { id: '/inscription'; path: '/inscription'; fullPath: '/inscription'; preLoaderRoute: typeof InscriptionRouteImport; parentRoute: typeof rootRouteImport }
    '/formations': { id: '/formations'; path: '/formations'; fullPath: '/formations'; preLoaderRoute: typeof FormationsRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/avis': { id: '/avis'; path: '/avis'; fullPath: '/avis'; preLoaderRoute: typeof AvisRouteImport; parentRoute: typeof rootRouteImport }
    '/agence': { id: '/agence'; path: '/agence'; fullPath: '/agence'; preLoaderRoute: typeof AgenceRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AgenceRoute,
  AvisRoute,
  ContactRoute,
  FormationsRoute,
  InscriptionRoute,
  MentionsLegalesRoute,
  VerificationTechniqueRoute,
  SitemapDotxmlRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addRouteTypes<FileRouteTypes>()
