/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationTechniqueRouteImport } from './routes/verification-technique'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGoogleRatingRouteImport } from './routes/api/google-rating'

const VerificationTechniqueRoute = VerificationTechniqueRouteImport.update({
  id: '/verification-technique',
  path: '/verification-technique',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceRoute = AgenceRouteImport.update({
  id: '/agence',
  path: '/agence',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleRatingRoute = ApiGoogleRatingRouteImport.update({
  id: '/api/google-rating',
  path: '/api/google-rating',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/api/google-rating': typeof ApiGoogleRatingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/api/google-rating': typeof ApiGoogleRatingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/agence': typeof AgenceRoute
  '/avis': typeof AvisRoute
  '/contact': typeof ContactRoute
  '/formations': typeof FormationsRoute
  '/inscription': typeof InscriptionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/verification-technique': typeof VerificationTechniqueRoute
  '/api/google-rating': typeof ApiGoogleRatingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/agence'
    | '/avis'
    | '/contact'
    | '/formations'
    | '/inscription'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-technique'
    | '/api/google-rating'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/agence'
    | '/avis'
    | '/contact'
    | '/formations'
    | '/inscription'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-technique'
    | '/api/google-rating'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/agence'
    | '/avis'
    | '/contact'
    | '/formations'
    | '/inscription'
    | '/mentions-legales'
    | '/sitemap.xml'
    | '/tarifs'
    | '/verification-technique'
    | '/api/google-rating'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AgenceRoute: typeof AgenceRoute
  AvisRoute: typeof AvisRoute
  ContactRoute: typeof ContactRoute
  FormationsRoute: typeof FormationsRoute
  InscriptionRoute: typeof InscriptionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  VerificationTechniqueRoute: typeof VerificationTechniqueRoute
  ApiGoogleRatingRoute: typeof ApiGoogleRatingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification-technique': {
      id: '/verification-technique'
      path: '/verification-technique'
      fullPath: '/verification-technique'
      preLoaderRoute: typeof VerificationTechniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence': {
      id: '/agence'
      path: '/agence'
      fullPath: '/agence'
      preLoaderRoute: typeof AgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-rating': {
      id: '/api/google-rating'
      path: '/api/google-rating'
      fullPath: '/api/google-rating'
      preLoaderRoute: typeof ApiGoogleRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AgenceRoute: AgenceRoute,
  AvisRoute: AvisRoute,
  ContactRoute: ContactRoute,
  FormationsRoute: FormationsRoute,
  InscriptionRoute: InscriptionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  VerificationTechniqueRoute: VerificationTechniqueRoute,
  ApiGoogleRatingRoute: ApiGoogleRatingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
